### ISSUE TITLE
Please comment here to be added as a collaborator!

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/github-for-developers-2016-04#10]

**Comment by kjell1979** [comment]
Hi

**Comment by apoorva89** [comment]
hello

**Comment by ragna-s** [comment]
Hi

**Comment by SoidaPalacios** [comment]
hi

**Comment by atabh1** [comment]
ok

**Comment by Savanand** [comment]
Hi

**Comment by imaadkhan87** [comment]
ghgfhgf

**Comment by landisjw** [comment]
Hi!

**Comment by DanielDwyer** [comment]
Hello, I'm Daniel

**Comment by osowskit** [comment]
🍌 !!

**Comment by JWW-TDC** [comment]
Hello!

**Comment by imaadkhan87** [comment]
retgrtret

**Comment by Extragarbage** [comment]
Hello

**Comment by phaniarnab** [comment]
phaniarnab

**Comment by atagakch** [comment]
'Ello

**Comment by baharehtraining** [comment]
Hi

**Comment by ghost** [comment]
hi

**Comment by argyleskull** [comment]
hello

**Comment by gaikwad7amar** [comment]
Hello!!

**Comment by tkuennen** [comment]
:+1:

**Comment by soo-park** [comment]
Hello

**Comment by tcbyrd** [comment]
:+1:

**Comment by maru-villanueva** [comment]
hi there!

**Comment by sbarnekow** [comment]
me me me

**Comment by markhollingsworth** [comment]
hello world

**Comment by patricko-z2** [comment]
hello

**Comment by bennycardenas** [comment]
Yeah!

**Comment by sedona2000** [comment]
morning

**Comment by bsumali** [comment]
🔥

**Comment by stormy-petrel** [comment]
Hi

**Comment by pmitchell40** [comment]
hello there

**Comment by msirek2** [comment]
Hi

**Comment by awoodson13** [comment]
I am here!

**Comment by jrajagopl** [comment]
Hello Github!

**Comment by HotFrost** [comment]
test

**Comment by FailedFace** [comment]
Hello

**Comment by jerryhurst** [comment]
Need tissues for my issues.

**Comment by SoidaPalacios** [comment]
hi

**Comment by glennon** [comment]
:zap:  Yay!!!! :zap:

**Comment by xubenny** [comment]
nice

**Comment by amit-rakesh** [comment]
Hello all !

**Comment by ra186026** [comment]
Richard, I'm in!

**Comment by oranperion** [comment]
test

**Comment by msirek2** [comment]
hello

**Comment by dcgull** [comment]
¯_(ツ)_/¯

**Comment by SherryShuranHuang** [comment]
We can go faster

**Comment by zen3d** [comment]
Hi!

**Comment by DebeshNayak** [comment]
This comment box should be at the top to be more user friendly.

**Comment by zaps** [comment]
i like stories

**Comment by joshua-ayala** [comment]
Add me plz!

**Comment by wayuyao** [comment]
Hi

**Comment by meralaz** [comment]
hi

**Comment by lirontzp** [comment]
YO YO

**Comment by dt186001** [comment]
Stop!  Listen!

**Comment by patricko-z2** [comment]
hello.

**Comment by Guitarbum722** [comment]
Woo!

**Comment by loupendley** [comment]
I have no issues with this.

**Comment by AnnaPerion** [comment]
:)

**Comment by kevin-brewer** [comment]
I like turtles

**Comment by sabahulhassan** [comment]
Amazing

**Comment by wanggith** [comment]
Hello

**Comment by kcdoan** [comment]
Hello!

**Comment by past97** [comment]
Add me.

**Comment by brianamarie** [comment]
🎉

**Comment by phaniarnab** [comment]
check

**Comment by minhhangle** [comment]
hi there

**Comment by tdbsur** [comment]
hello

**Comment by vp186006** [comment]
testing.. 1, 2 , 3

**Comment by githubteacher** [comment]
:tada: @lirontzp, @dt186001, @Guitarbum722, @lp110118, @AnnaPerion, @kevin-brewer, @sabahulhassan, @wanggith, @kcdoan, @past97, @minhhangle, and @tdbsur are now  repository collaborators. :balloon:

**Comment by githubteacher** [comment]
:tada: @kjell1979, @api1234, @ragna-s, @SoidaPalacios, @atabh1, @Savanand, @imaadkhan87, @landisjw, @DanielDwyer, @osowskit, @JWW-TDC, @imaadkhan87, @Extragarbage, @phaniarnab, @atagakch, @baharehtraining, @goldenrico, @argyleskull, @gaikwad7amar, @tkuennen, @eatingbird, @tcbyrd, @maru-villanueva, @sbarnekow, @markhollingsworth, @patricko-z2, @bennycardenas, @sedona2000, @bsumali, @haiyantd, @pmitchell40, @msirek2, @awoodson13, @jrajagopl, @HotFrost, @FailedFace, @jerryhurst, @SoidaPalacios, @glennon, @xubenny, @amit-rakesh, @ra186026, @oranperion, @msirek2, @danseagull, @SherryShuranHuang, @zen3d, @DebeshNayak, @zaps, @badempire, @wayuyao, @meralaz, @lirontzp, @dt186001, @patricko-z2, @Guitarbum722, @lp110118, @AnnaPerion, @kevin-brewer, @sabahulhassan, @wanggith, @kcdoan, @past97, and @phaniarnab are now  repository collaborators. :balloon:

**Comment by githubteacher** [comment]
:tada: @vp186006 is now a repository collaborator. :balloon:

**Comment by bhooshan786** [comment]
hi

**Comment by githubteacher** [comment]
:tada: @bhooshan786 is now a repository collaborator. :balloon:

**Comment by tdbip** [comment]
hey all

**Comment by githubteacher** [comment]
:tada: @tdbip is now a repository collaborator. :balloon:

**Comment by MelodyBishop** [comment]
hello

**Comment by johannhj** [comment]
howdy!

**Comment by vharsh** [comment]
Hello..SOrry i am late..

**Comment by githubteacher** [comment]
:tada: @MelodyBishop, @johannhj, and @vharsh are now  repository collaborators. :balloon:

**Comment by MelodyBishop** [comment]
Thank you

**Comment by geoffcode** [comment]
Hello world

**Comment by jns111** [comment]
Hi

**Comment by githubteacher** [comment]
:tada: @jns111 is now a repository collaborator. :balloon:

**Comment by ashutoshbaghel** [comment]
Please add me as well # :)

**Comment by githubteacher** [comment]
:tada: @ashutoshbaghel is now a repository collaborator. :balloon:

**Comment by andrewpett** [comment]
hi

**Comment by githubteacher** [comment]
:tada: @andrewpett is now a repository collaborator. :balloon:

**Comment by bhaveshph** [comment]
new comment here thanks

**Comment by githubteacher** [comment]
:tada: @bhaveshph is now a repository collaborator. :balloon:

**Comment by yingyuwang** [comment]
hi

**Comment by githubteacher** [comment]
:tada: @yingyuwang is now a repository collaborator. :balloon:

**Comment by kandaaaaa** [comment]
hi

**Comment by githubteacher** [comment]
:tada: @kandaaaaa is now a repository collaborator. :balloon:

**Comment by andrewxz** [comment]
git push origin not work for me

git push origin andrewxz-0
Username for 'https://github.com': andrewxz
Password for 'https://andrewxz@github.com':
remote: Permission to githubteacher/github-for-developers-2016-04.git denied to andrewxz.
fatal: unable to access 'https://github.com/githubteacher/github-for-developers-2016-04.git/': The requested URL returned error: 403

**Comment by githubteacher** [comment]
:tada: @andrewxz is now a repository collaborator. :balloon:

**Comment by andrewxz** [comment]
thanks. works now

**Comment by justinjosecjj** [comment]
Hello

**Comment by cy4112016** [comment]
Finally get to the right issue.  I need to add myself to this issue.

**Comment by githubteacher** [comment]
:tada: @justinjosecjj and @cy4112016 are now  repository collaborators. :balloon:

**Comment by cy4112016** [comment]
@cy4112016 is this added in ?  I need to be verify :Tada:

**Comment by githubteacher** [comment]
:tada: @garcher42 is now a repository collaborator. :balloon:

**Comment by vmsynkov-zz** [comment]
boom

**Comment by githubteacher** [comment]
:tada: @vmsynkov is now a repository collaborator. :balloon:

**Comment by yingyuwang** [comment]
Have I ?

**Comment by hcanna** [comment]
@yingyuwang ... Yes it shows you as a collaborator

**Comment by jdkjoel** [comment]
can i please added

**Comment by githubteacher** [comment]
:tada: @jdkjoel is now a repository collaborator. :balloon:

**Comment by cy4112016** [comment]
@cy4112016 need to be repository collaborator 💯 
Why I did not see my pull request ?!

**Comment by w7lish** [comment]
need to be repository collaborator

**Comment by githubteacher** [comment]
:tada: @w7lish is now a repository collaborator. :balloon:

**Comment by jman2000** [comment]
Need to be added

**Comment by githubteacher** [comment]
:tada: @jman2000 is now a repository collaborator. :balloon:

**Comment by tdbsur** [comment]
tdbsur

**Comment by dariushazimi** [comment]
please add me
